# This workflow will run integrations tests daily at midnight.

name: Daily CI

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: Daily Server Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        server:
          [
            as-hk-1,
            eu-fin-2,
            eu-ger-3,
            eu-ger-4,
            eu-ger-5,
            eu-ger-6,
            eu-ger-7,
            eu-ger-8,
            eu-pol-1,
            eu-pol-2,
            eu-pol-3,
            us-or-1,
            us-or-2,
            us-pa-2,
            us-va-1,
            us-va-2,
            us-va-3,
          ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn

      - name: Integration test on server
        run: yarn run jest src/integration.test.ts
        env:
          SKYNET_JS_INTEGRATION_TEST_SERVER: "https://${{ matrix.server }}.siasky.net"

  test-dev:
    name: Daily Dev Server Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dev-server: [siasky.dev, siasky.xyz]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn

      - name: Integration test on dev server
        run: yarn run jest src/integration.test.ts
        env:
          SKYNET_JS_INTEGRATION_TEST_SERVER: "https://${{ matrix.dev-server }}"
