# This workflow will run integrations tests daily at midnight.

name: Daily CI

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: Daily Server Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server:
          [eu-fin-1, eu-fin-2, eu-ger-1, eu-ger-2, eu-ger-3, eu-ger-4, us-or-1, us-or-2, us-pa-1, us-pa-2, us-va-1]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn

      - name: Integration test on server
        run: yarn run jest src/integration.test.ts
        env:
          SKYNET_JS_INTEGRATION_TEST_SERVER: "https://${{ matrix.server }}.siasky.net"
